// import { AlbumCard } from './components/AlbumCard/AlbumCard';
import { PayPalPayment } from './components/PayPalPayment/PayPalPayment';
import {ButtonGoogleLogin} from './components/ButtonGoogleLogin/ButtonGoogleLogin';
import {LoginBasic} from './components/LoginBasic/LoginBasic';
import { ProgressSpinner } from './components/ProgressSpinner/ProgressSpinner';
import { Button } from './components/Button/Button';
import { DivisoryLine } from './components/DivisoryLine/DivisoryLine';
import { Dialog } from './components/Dialog/Dialog';
import { Card } from './components/Card/Card';
import { Navbar } from './components/Navbar/Navbar';

// export { AlbumCard };
export { PayPalPayment };
export {ButtonGoogleLogin};
export {LoginBasic};
export {ProgressSpinner};
export {Button};
export {DivisoryLine};
export {Dialog};
export {Card};
export { Navbar};
